/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface AddNode {
  left: string
  right: string
}
export interface MultNode {
  left: string
  right: string
}
export interface Ast {
  left: AddNode
  right: MultNode
}
export function printAsNapiObj(): Ast
export function printAsString(): string
export function printAsValue(): any
