/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface User {
  name: string
  age: number
}
export function print(user: User): void
